# This file was auto-generated by Fern from our API Definition.

import typing

FileWatchWaitRequestEventTypesItem = typing.Union[
    typing.Literal["create", "write", "remove", "rename", "chmod"], typing.Any
]
