// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as Sandbox from "../../../index.js";

export declare namespace Bash {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class Bash {
    protected readonly _options: Bash.Options;

    constructor(_options: Bash.Options) {
        this._options = _options;
    }

    /**
     * Execute a bash command.
     *
     * - async_mode=true: returns immediately with RUNNING status
     * - async_mode=false + timeout: waits up to timeout, then returns RUNNING if not done
     * - async_mode=false + no timeout: waits until command completes
     * - hard_timeout: kills the process after this many seconds
     * - env: extra environment variables for this command only
     *
     * @param {Sandbox.BashExecRequest} request
     * @param {Bash.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.bash.bashExec({
     *         command: "command"
     *     })
     */
    public bashExec(
        request: Sandbox.BashExecRequest,
        requestOptions?: Bash.RequestOptions,
    ): core.HttpResponsePromise<core.APIResponse<Sandbox.ResponseBashExecResult, Sandbox.bash.bashExec.Error>> {
        return core.HttpResponsePromise.fromPromise(this.__bashExec(request, requestOptions));
    }

    private async __bashExec(
        request: Sandbox.BashExecRequest,
        requestOptions?: Bash.RequestOptions,
    ): Promise<core.WithRawResponse<core.APIResponse<Sandbox.ResponseBashExecResult, Sandbox.bash.bashExec.Error>>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/bash/exec",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: {
                    ok: true,
                    body: _response.body as Sandbox.ResponseBashExecResult,
                    headers: _response.headers,
                    rawResponse: _response.rawResponse,
                },
                rawResponse: _response.rawResponse,
            };
        }

        if (!_response.ok && core.isFailedResponse(_response) && _response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    return {
                        data: {
                            ok: false,
                            error: Sandbox.bash.bashExec.Error.unprocessableEntityError(
                                _response.error.body as Sandbox.HttpValidationError,
                            ),
                            rawResponse: _response.rawResponse,
                        },
                        rawResponse: _response.rawResponse,
                    };
            }
        }

        return {
            data: {
                ok: false,
                error: Sandbox.bash.bashExec.Error._unknown(core.isFailedResponse(_response) ? _response.error : { reason: "unknown", errorMessage: "Unknown error" }),
                rawResponse: _response.rawResponse,
            },
            rawResponse: _response.rawResponse,
        };
    }

    /**
     * Read output from a bash session using offset-based streaming.
     *
     * - offset/stderr_offset: byte offsets to read from (use values from previous response)
     * - wait=true: long-poll until new output arrives or wait_timeout
     *
     * @param {Sandbox.BashOutputRequest} request
     * @param {Bash.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.bash.bashOutput({
     *         session_id: "session_id"
     *     })
     */
    public bashOutput(
        request: Sandbox.BashOutputRequest,
        requestOptions?: Bash.RequestOptions,
    ): core.HttpResponsePromise<core.APIResponse<Sandbox.ResponseBashOutputResult, Sandbox.bash.bashOutput.Error>> {
        return core.HttpResponsePromise.fromPromise(this.__bashOutput(request, requestOptions));
    }

    private async __bashOutput(
        request: Sandbox.BashOutputRequest,
        requestOptions?: Bash.RequestOptions,
    ): Promise<
        core.WithRawResponse<core.APIResponse<Sandbox.ResponseBashOutputResult, Sandbox.bash.bashOutput.Error>>
    > {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/bash/output",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: {
                    ok: true,
                    body: _response.body as Sandbox.ResponseBashOutputResult,
                    headers: _response.headers,
                    rawResponse: _response.rawResponse,
                },
                rawResponse: _response.rawResponse,
            };
        }

        if (!_response.ok && core.isFailedResponse(_response) && _response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    return {
                        data: {
                            ok: false,
                            error: Sandbox.bash.bashOutput.Error.unprocessableEntityError(
                                _response.error.body as Sandbox.HttpValidationError,
                            ),
                            rawResponse: _response.rawResponse,
                        },
                        rawResponse: _response.rawResponse,
                    };
            }
        }

        return {
            data: {
                ok: false,
                error: Sandbox.bash.bashOutput.Error._unknown(core.isFailedResponse(_response) ? _response.error : { reason: "unknown", errorMessage: "Unknown error" }),
                rawResponse: _response.rawResponse,
            },
            rawResponse: _response.rawResponse,
        };
    }

    /**
     * Write input to a bash session's stdin.
     *
     * @param {Sandbox.BashWriteRequest} request
     * @param {Bash.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.bash.bashWrite({
     *         session_id: "session_id",
     *         input: "input"
     *     })
     */
    public bashWrite(
        request: Sandbox.BashWriteRequest,
        requestOptions?: Bash.RequestOptions,
    ): core.HttpResponsePromise<core.APIResponse<Sandbox.Response, Sandbox.bash.bashWrite.Error>> {
        return core.HttpResponsePromise.fromPromise(this.__bashWrite(request, requestOptions));
    }

    private async __bashWrite(
        request: Sandbox.BashWriteRequest,
        requestOptions?: Bash.RequestOptions,
    ): Promise<core.WithRawResponse<core.APIResponse<Sandbox.Response, Sandbox.bash.bashWrite.Error>>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/bash/write",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: {
                    ok: true,
                    body: _response.body as Sandbox.Response,
                    headers: _response.headers,
                    rawResponse: _response.rawResponse,
                },
                rawResponse: _response.rawResponse,
            };
        }

        if (!_response.ok && core.isFailedResponse(_response) && _response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    return {
                        data: {
                            ok: false,
                            error: Sandbox.bash.bashWrite.Error.unprocessableEntityError(
                                _response.error.body as Sandbox.HttpValidationError,
                            ),
                            rawResponse: _response.rawResponse,
                        },
                        rawResponse: _response.rawResponse,
                    };
            }
        }

        return {
            data: {
                ok: false,
                error: Sandbox.bash.bashWrite.Error._unknown(core.isFailedResponse(_response) ? _response.error : { reason: "unknown", errorMessage: "Unknown error" }),
                rawResponse: _response.rawResponse,
            },
            rawResponse: _response.rawResponse,
        };
    }

    /**
     * Send a signal to a bash session's process.
     *
     * @param {Sandbox.BashKillRequest} request
     * @param {Bash.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.bash.bashKill({
     *         session_id: "session_id"
     *     })
     */
    public bashKill(
        request: Sandbox.BashKillRequest,
        requestOptions?: Bash.RequestOptions,
    ): core.HttpResponsePromise<core.APIResponse<Sandbox.Response, Sandbox.bash.bashKill.Error>> {
        return core.HttpResponsePromise.fromPromise(this.__bashKill(request, requestOptions));
    }

    private async __bashKill(
        request: Sandbox.BashKillRequest,
        requestOptions?: Bash.RequestOptions,
    ): Promise<core.WithRawResponse<core.APIResponse<Sandbox.Response, Sandbox.bash.bashKill.Error>>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/bash/kill",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: {
                    ok: true,
                    body: _response.body as Sandbox.Response,
                    headers: _response.headers,
                    rawResponse: _response.rawResponse,
                },
                rawResponse: _response.rawResponse,
            };
        }

        if (!_response.ok && core.isFailedResponse(_response) && _response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    return {
                        data: {
                            ok: false,
                            error: Sandbox.bash.bashKill.Error.unprocessableEntityError(
                                _response.error.body as Sandbox.HttpValidationError,
                            ),
                            rawResponse: _response.rawResponse,
                        },
                        rawResponse: _response.rawResponse,
                    };
            }
        }

        return {
            data: {
                ok: false,
                error: Sandbox.bash.bashKill.Error._unknown(core.isFailedResponse(_response) ? _response.error : { reason: "unknown", errorMessage: "Unknown error" }),
                rawResponse: _response.rawResponse,
            },
            rawResponse: _response.rawResponse,
        };
    }

    /**
     * List all active bash sessions.
     *
     * @param {Bash.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.bash.bashSessions()
     */
    public bashSessions(
        requestOptions?: Bash.RequestOptions,
    ): core.HttpResponsePromise<
        core.APIResponse<Sandbox.ResponseListBashSessionInfo, Sandbox.bash.bashSessions.Error>
    > {
        return core.HttpResponsePromise.fromPromise(this.__bashSessions(requestOptions));
    }

    private async __bashSessions(
        requestOptions?: Bash.RequestOptions,
    ): Promise<
        core.WithRawResponse<core.APIResponse<Sandbox.ResponseListBashSessionInfo, Sandbox.bash.bashSessions.Error>>
    > {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/bash/sessions",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: {
                    ok: true,
                    body: _response.body as Sandbox.ResponseListBashSessionInfo,
                    headers: _response.headers,
                    rawResponse: _response.rawResponse,
                },
                rawResponse: _response.rawResponse,
            };
        }

        return {
            data: {
                ok: false,
                error: Sandbox.bash.bashSessions.Error._unknown(core.isFailedResponse(_response) ? _response.error : { reason: "unknown", errorMessage: "Unknown error" }),
                rawResponse: _response.rawResponse,
            },
            rawResponse: _response.rawResponse,
        };
    }

    /**
     * Create a new bash session.
     *
     * @param {Sandbox.BashSessionCreateRequest} request
     * @param {Bash.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.bash.bashCreateSession()
     */
    public bashCreateSession(
        request: Sandbox.BashSessionCreateRequest = {},
        requestOptions?: Bash.RequestOptions,
    ): core.HttpResponsePromise<
        core.APIResponse<Sandbox.ResponseBashSessionInfo, Sandbox.bash.bashCreateSession.Error>
    > {
        return core.HttpResponsePromise.fromPromise(this.__bashCreateSession(request, requestOptions));
    }

    private async __bashCreateSession(
        request: Sandbox.BashSessionCreateRequest = {},
        requestOptions?: Bash.RequestOptions,
    ): Promise<
        core.WithRawResponse<core.APIResponse<Sandbox.ResponseBashSessionInfo, Sandbox.bash.bashCreateSession.Error>>
    > {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/bash/sessions/create",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: {
                    ok: true,
                    body: _response.body as Sandbox.ResponseBashSessionInfo,
                    headers: _response.headers,
                    rawResponse: _response.rawResponse,
                },
                rawResponse: _response.rawResponse,
            };
        }

        if (!_response.ok && core.isFailedResponse(_response) && _response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    return {
                        data: {
                            ok: false,
                            error: Sandbox.bash.bashCreateSession.Error.unprocessableEntityError(
                                _response.error.body as Sandbox.HttpValidationError,
                            ),
                            rawResponse: _response.rawResponse,
                        },
                        rawResponse: _response.rawResponse,
                    };
            }
        }

        return {
            data: {
                ok: false,
                error: Sandbox.bash.bashCreateSession.Error._unknown(core.isFailedResponse(_response) ? _response.error : { reason: "unknown", errorMessage: "Unknown error" }),
                rawResponse: _response.rawResponse,
            },
            rawResponse: _response.rawResponse,
        };
    }

    /**
     * Close a bash session.
     *
     * @param {string} sessionId
     * @param {Bash.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.bash.bashCloseSession("session_id")
     */
    public bashCloseSession(
        sessionId: string,
        requestOptions?: Bash.RequestOptions,
    ): core.HttpResponsePromise<core.APIResponse<Sandbox.Response, Sandbox.bash.bashCloseSession.Error>> {
        return core.HttpResponsePromise.fromPromise(this.__bashCloseSession(sessionId, requestOptions));
    }

    private async __bashCloseSession(
        sessionId: string,
        requestOptions?: Bash.RequestOptions,
    ): Promise<core.WithRawResponse<core.APIResponse<Sandbox.Response, Sandbox.bash.bashCloseSession.Error>>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v1/bash/sessions/${core.url.encodePathParam(sessionId)}/close`,
            ),
            method: "POST",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: {
                    ok: true,
                    body: _response.body as Sandbox.Response,
                    headers: _response.headers,
                    rawResponse: _response.rawResponse,
                },
                rawResponse: _response.rawResponse,
            };
        }

        if (!_response.ok && core.isFailedResponse(_response) && _response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    return {
                        data: {
                            ok: false,
                            error: Sandbox.bash.bashCloseSession.Error.unprocessableEntityError(
                                _response.error.body as Sandbox.HttpValidationError,
                            ),
                            rawResponse: _response.rawResponse,
                        },
                        rawResponse: _response.rawResponse,
                    };
            }
        }

        return {
            data: {
                ok: false,
                error: Sandbox.bash.bashCloseSession.Error._unknown(core.isFailedResponse(_response) ? _response.error : { reason: "unknown", errorMessage: "Unknown error" }),
                rawResponse: _response.rawResponse,
            },
            rawResponse: _response.rawResponse,
        };
    }
}
