// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as errors from "../../../../errors/index.js";
import * as Sandbox from "../../../index.js";

export declare namespace Mcp {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class Mcp {
    protected readonly _options: Mcp.Options;

    constructor(_options: Mcp.Options) {
        this._options = _options;
    }

    /**
     * List all available tools from the specified MCP server
     *
     * Args:
     *     server_name: The name of the MCP server as defined in mcp-servers.json
     *
     * Returns:
     *     Response containing the list of available tools with their descriptions and parameters
     *
     * @param {string} serverName - Name of the MCP server
     * @param {Mcp.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Sandbox.UnprocessableEntityError}
     *
     * @example
     *     await client.mcp.listMcpTools("server_name")
     */
    public listMcpTools(
        serverName: string,
        requestOptions?: Mcp.RequestOptions,
    ): core.HttpResponsePromise<Sandbox.ResponseListToolsResultModel> {
        return core.HttpResponsePromise.fromPromise(this.__listMcpTools(serverName, requestOptions));
    }

    private async __listMcpTools(
        serverName: string,
        requestOptions?: Mcp.RequestOptions,
    ): Promise<core.WithRawResponse<Sandbox.ResponseListToolsResultModel>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v1/mcp/${core.url.encodePathParam(serverName)}/tools`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Sandbox.ResponseListToolsResultModel, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Sandbox.UnprocessableEntityError(
                        _response.error.body as Sandbox.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.SandboxError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SandboxError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SandboxTimeoutError("Timeout exceeded when calling GET /v1/mcp/{server_name}/tools.");
            case "unknown":
                throw new errors.SandboxError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Execute a specific tool on the specified MCP server
     *
     * Args:
     *     server_name: The name of the MCP server as defined in mcp-servers.json
     *     tool_name: The name of the tool to execute
     *     arguments: Tool arguments dictionary
     *
     * Returns:
     *     Response containing the tool execution results
     *
     * @param {string} serverName - Name of the MCP server
     * @param {string} toolName - Name of the tool to execute
     * @param {Record<string, unknown>} request
     * @param {Mcp.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Sandbox.UnprocessableEntityError}
     *
     * @example
     *     await client.mcp.executeMcpTool("server_name", "tool_name", {
     *         "key": "value"
     *     })
     */
    public executeMcpTool(
        serverName: string,
        toolName: string,
        request: Record<string, unknown>,
        requestOptions?: Mcp.RequestOptions,
    ): core.HttpResponsePromise<Sandbox.ResponseCallToolResultModel> {
        return core.HttpResponsePromise.fromPromise(
            this.__executeMcpTool(serverName, toolName, request, requestOptions),
        );
    }

    private async __executeMcpTool(
        serverName: string,
        toolName: string,
        request: Record<string, unknown>,
        requestOptions?: Mcp.RequestOptions,
    ): Promise<core.WithRawResponse<Sandbox.ResponseCallToolResultModel>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v1/mcp/${core.url.encodePathParam(serverName)}/tools/${core.url.encodePathParam(toolName)}`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Sandbox.ResponseCallToolResultModel, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Sandbox.UnprocessableEntityError(
                        _response.error.body as Sandbox.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.SandboxError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SandboxError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SandboxTimeoutError(
                    "Timeout exceeded when calling POST /v1/mcp/{server_name}/tools/{tool_name}.",
                );
            case "unknown":
                throw new errors.SandboxError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * List all configured MCP servers
     *
     * Returns:
     *     Response containing the list of configured and filtered MCP servers
     *
     * @param {Mcp.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.mcp.listMcpServers()
     */
    public listMcpServers(requestOptions?: Mcp.RequestOptions): core.HttpResponsePromise<Sandbox.ResponseListStr> {
        return core.HttpResponsePromise.fromPromise(this.__listMcpServers(requestOptions));
    }

    private async __listMcpServers(
        requestOptions?: Mcp.RequestOptions,
    ): Promise<core.WithRawResponse<Sandbox.ResponseListStr>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/mcp/servers",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Sandbox.ResponseListStr, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.SandboxError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SandboxError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SandboxTimeoutError("Timeout exceeded when calling GET /v1/mcp/servers.");
            case "unknown":
                throw new errors.SandboxError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }
}
