// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as errors from "../../../../errors/index.js";
import * as Sandbox from "../../../index.js";

export declare namespace Skills {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class Skills {
    protected readonly _options: Skills.Options;

    constructor(_options: Skills.Options) {
        this._options = _options;
    }

    /**
     * @param {Sandbox.BodyRegisterSkills} request
     * @param {Skills.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Sandbox.UnprocessableEntityError}
     *
     * @example
     *     import { createReadStream } from "fs";
     *     await client.skills.registerSkills({})
     */
    public registerSkills(
        request: Sandbox.BodyRegisterSkills,
        requestOptions?: Skills.RequestOptions,
    ): core.HttpResponsePromise<Sandbox.ResponseSkillRegistrationResult> {
        return core.HttpResponsePromise.fromPromise(this.__registerSkills(request, requestOptions));
    }

    private async __registerSkills(
        request: Sandbox.BodyRegisterSkills,
        requestOptions?: Skills.RequestOptions,
    ): Promise<core.WithRawResponse<Sandbox.ResponseSkillRegistrationResult>> {
        const _request = await core.newFormData();
        if (request.file != null) {
            await _request.appendFile("file", request.file);
        }

        if (request.path != null) {
            _request.append("path", request.path);
        }

        if (request.name != null) {
            _request.append("name", request.name);
        }

        const _maybeEncodedRequest = await _request.getRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ..._maybeEncodedRequest.headers }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/skills/register",
            ),
            method: "POST",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            requestType: "file",
            duplex: _maybeEncodedRequest.duplex,
            body: _maybeEncodedRequest.body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as Sandbox.ResponseSkillRegistrationResult,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Sandbox.UnprocessableEntityError(
                        _response.error.body as Sandbox.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.SandboxError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SandboxError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SandboxTimeoutError("Timeout exceeded when calling POST /v1/skills/register.");
            case "unknown":
                throw new errors.SandboxError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {Sandbox.SkillsListMetadataRequest} request
     * @param {Skills.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Sandbox.UnprocessableEntityError}
     *
     * @example
     *     await client.skills.listMetadata({
     *         names: "names"
     *     })
     */
    public listMetadata(
        request: Sandbox.SkillsListMetadataRequest = {},
        requestOptions?: Skills.RequestOptions,
    ): core.HttpResponsePromise<Sandbox.ResponseSkillMetadataCollection> {
        return core.HttpResponsePromise.fromPromise(this.__listMetadata(request, requestOptions));
    }

    private async __listMetadata(
        request: Sandbox.SkillsListMetadataRequest = {},
        requestOptions?: Skills.RequestOptions,
    ): Promise<core.WithRawResponse<Sandbox.ResponseSkillMetadataCollection>> {
        const { names } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (names != null) {
            _queryParams.names = names;
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/skills/metadatas",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as Sandbox.ResponseSkillMetadataCollection,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Sandbox.UnprocessableEntityError(
                        _response.error.body as Sandbox.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.SandboxError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SandboxError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SandboxTimeoutError("Timeout exceeded when calling GET /v1/skills/metadatas.");
            case "unknown":
                throw new errors.SandboxError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {Skills.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.skills.clearSkills()
     */
    public clearSkills(requestOptions?: Skills.RequestOptions): core.HttpResponsePromise<Sandbox.ResponseDict> {
        return core.HttpResponsePromise.fromPromise(this.__clearSkills(requestOptions));
    }

    private async __clearSkills(
        requestOptions?: Skills.RequestOptions,
    ): Promise<core.WithRawResponse<Sandbox.ResponseDict>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/skills",
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Sandbox.ResponseDict, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.SandboxError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SandboxError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SandboxTimeoutError("Timeout exceeded when calling DELETE /v1/skills.");
            case "unknown":
                throw new errors.SandboxError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {string} name
     * @param {Skills.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Sandbox.UnprocessableEntityError}
     *
     * @example
     *     await client.skills.deleteSkill("name")
     */
    public deleteSkill(
        name: string,
        requestOptions?: Skills.RequestOptions,
    ): core.HttpResponsePromise<Sandbox.ResponseSkillMetadata> {
        return core.HttpResponsePromise.fromPromise(this.__deleteSkill(name, requestOptions));
    }

    private async __deleteSkill(
        name: string,
        requestOptions?: Skills.RequestOptions,
    ): Promise<core.WithRawResponse<Sandbox.ResponseSkillMetadata>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v1/skills/${core.url.encodePathParam(name)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Sandbox.ResponseSkillMetadata, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Sandbox.UnprocessableEntityError(
                        _response.error.body as Sandbox.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.SandboxError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SandboxError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SandboxTimeoutError("Timeout exceeded when calling DELETE /v1/skills/{name}.");
            case "unknown":
                throw new errors.SandboxError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {string} name
     * @param {Skills.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Sandbox.UnprocessableEntityError}
     *
     * @example
     *     await client.skills.getContent("name")
     */
    public getContent(
        name: string,
        requestOptions?: Skills.RequestOptions,
    ): core.HttpResponsePromise<Sandbox.ResponseSkillContentResult> {
        return core.HttpResponsePromise.fromPromise(this.__getContent(name, requestOptions));
    }

    private async __getContent(
        name: string,
        requestOptions?: Skills.RequestOptions,
    ): Promise<core.WithRawResponse<Sandbox.ResponseSkillContentResult>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v1/skills/${core.url.encodePathParam(name)}/content`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Sandbox.ResponseSkillContentResult, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Sandbox.UnprocessableEntityError(
                        _response.error.body as Sandbox.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.SandboxError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SandboxError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SandboxTimeoutError("Timeout exceeded when calling GET /v1/skills/{name}/content.");
            case "unknown":
                throw new errors.SandboxError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }
}
