// This file was auto-generated by Fern from our API Definition.

export const FileWatchWaitRequestEventTypesItem = {
    Create: "create",
    Write: "write",
    Remove: "remove",
    Rename: "rename",
    Chmod: "chmod",
} as const;
export type FileWatchWaitRequestEventTypesItem =
    (typeof FileWatchWaitRequestEventTypesItem)[keyof typeof FileWatchWaitRequestEventTypesItem];
