// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as errors from "../../../../errors/index.js";
import * as Sandbox from "../../../index.js";

export declare namespace Nodejs {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class Nodejs {
    protected readonly _options: Nodejs.Options;

    constructor(_options: Nodejs.Options) {
        this._options = _options;
    }

    /**
     * Execute JavaScript code using Node.js
     *
     * This endpoint allows you to execute JavaScript code and get results back.
     * Each request creates a fresh execution environment that's cleaned up automatically.
     *
     * @param {Sandbox.NodeJsExecuteRequest} request
     * @param {Nodejs.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Sandbox.UnprocessableEntityError}
     *
     * @example
     *     await client.nodejs.executeCode({
     *         code: "code"
     *     })
     */
    public executeCode(
        request: Sandbox.NodeJsExecuteRequest,
        requestOptions?: Nodejs.RequestOptions,
    ): core.HttpResponsePromise<Sandbox.ResponseNodeJsExecuteResponse> {
        return core.HttpResponsePromise.fromPromise(this.__executeCode(request, requestOptions));
    }

    private async __executeCode(
        request: Sandbox.NodeJsExecuteRequest,
        requestOptions?: Nodejs.RequestOptions,
    ): Promise<core.WithRawResponse<Sandbox.ResponseNodeJsExecuteResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/nodejs/execute",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as Sandbox.ResponseNodeJsExecuteResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Sandbox.UnprocessableEntityError(
                        _response.error.body as Sandbox.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.SandboxError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SandboxError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SandboxTimeoutError("Timeout exceeded when calling POST /v1/nodejs/execute.");
            case "unknown":
                throw new errors.SandboxError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Get information about Node.js runtime and available languages
     *
     * @param {Nodejs.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.nodejs.getInfo()
     */
    public getInfo(
        requestOptions?: Nodejs.RequestOptions,
    ): core.HttpResponsePromise<Sandbox.ResponseNodeJsRuntimeInfo> {
        return core.HttpResponsePromise.fromPromise(this.__getInfo(requestOptions));
    }

    private async __getInfo(
        requestOptions?: Nodejs.RequestOptions,
    ): Promise<core.WithRawResponse<Sandbox.ResponseNodeJsRuntimeInfo>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/nodejs/info",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Sandbox.ResponseNodeJsRuntimeInfo, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.SandboxError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SandboxError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SandboxTimeoutError("Timeout exceeded when calling GET /v1/nodejs/info.");
            case "unknown":
                throw new errors.SandboxError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }
}
