// This file was auto-generated by Fern from our API Definition.

export interface Annotations {
    audience?: Annotations.Audience.Item[];
    priority?: number;
    /** Accepts any additional properties */
    [key: string]: any;
}

export namespace Annotations {
    export type Audience = Audience.Item[];

    export namespace Audience {
        export const Item = {
            User: "user",
            Assistant: "assistant",
        } as const;
        export type Item = (typeof Item)[keyof typeof Item];
    }
}
