// This file was auto-generated by Fern from our API Definition.

/**
 * Binary contents of a resource.
 */
export interface BlobResourceContents {
    uri: string;
    mimeType?: string;
    _meta?: Record<string, any>;
    blob: string;
    /** Accepts any additional properties */
    [key: string]: any;
}
