// This file was auto-generated by Fern from our API Definition.

export interface ClickAction {
    x?: number;
    y?: number;
    button?: ClickAction.Button;
    num_clicks?: number;
}

export namespace ClickAction {
    export const Button = {
        Left: "left",
        Right: "right",
        Middle: "middle",
    } as const;
    export type Button = (typeof Button)[keyof typeof Button];
}
