// This file was auto-generated by Fern from our API Definition.

export interface MouseDownAction {
    button?: MouseDownAction.Button;
}

export namespace MouseDownAction {
    export const Button = {
        Left: "left",
        Right: "right",
        Middle: "middle",
    } as const;
    export type Button = (typeof Button)[keyof typeof Button];
}
