// This file was auto-generated by Fern from our API Definition.

export interface MouseUpAction {
    button?: MouseUpAction.Button;
}

export namespace MouseUpAction {
    export const Button = {
        Left: "left",
        Right: "right",
        Middle: "middle",
    } as const;
    export type Button = (typeof Button)[keyof typeof Button];
}
