// This file was auto-generated by Fern from our API Definition.

import type * as Sandbox from "../index.js";

export interface ResponseCallToolResultModel {
    /** Whether the operation was successful */
    success?: boolean;
    /** Operation result message */
    message?: string;
    /** Data returned from the operation */
    data?: ResponseCallToolResultModel.Data;
}

export namespace ResponseCallToolResultModel {
    /**
     * The server's response to a tool call.
     */
    export interface Data {
        _meta?: Record<string, any>;
        content: Sandbox.ResponseCallToolResultModelDataContentItem[];
        structuredContent?: Record<string, any>;
        isError?: boolean;
        /** Accepts any additional properties */
        [key: string]: any;
    }
}
