// This file was auto-generated by Fern from our API Definition.

import type * as Sandbox from "../index.js";

export interface ResponseListToolsResultModel {
    /** Whether the operation was successful */
    success?: boolean;
    /** Operation result message */
    message?: string;
    /** Data returned from the operation */
    data?: ResponseListToolsResultModel.Data;
}

export namespace ResponseListToolsResultModel {
    /**
     * The server's response to a tools/list request from the client.
     */
    export interface Data {
        _meta?: Record<string, any>;
        nextCursor?: string;
        tools: Sandbox.Tool[];
        /** Accepts any additional properties */
        [key: string]: any;
    }
}
