// This file was auto-generated by Fern from our API Definition.

import type * as Sandbox from "../index.js";

/**
 * Definition for a tool the client can call.
 */
export interface Tool {
    name: string;
    title?: string;
    description?: string;
    inputSchema: Record<string, any>;
    outputSchema?: Record<string, any>;
    icons?: Sandbox.Icon[];
    annotations?: Sandbox.ToolAnnotations;
    _meta?: Record<string, any>;
    /** Accepts any additional properties */
    [key: string]: any;
}
