// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as errors from "../../../../errors/index.js";
import * as Sandbox from "../../../index.js";

export declare namespace Util {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class Util {
    protected readonly _options: Util.Options;

    constructor(_options: Util.Options) {
        this._options = _options;
    }

    /**
     * Convert a given URI to Markdown format
     *
     * @param {Sandbox.UtilConvertToMarkdownRequest} request
     * @param {Util.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Sandbox.UnprocessableEntityError}
     *
     * @example
     *     await client.util.convertToMarkdown({
     *         uri: "uri"
     *     })
     */
    public convertToMarkdown(
        request: Sandbox.UtilConvertToMarkdownRequest,
        requestOptions?: Util.RequestOptions,
    ): core.HttpResponsePromise<Sandbox.Response> {
        return core.HttpResponsePromise.fromPromise(this.__convertToMarkdown(request, requestOptions));
    }

    private async __convertToMarkdown(
        request: Sandbox.UtilConvertToMarkdownRequest,
        requestOptions?: Util.RequestOptions,
    ): Promise<core.WithRawResponse<Sandbox.Response>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/util/convert_to_markdown",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Sandbox.Response, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Sandbox.UnprocessableEntityError(
                        _response.error.body as Sandbox.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.SandboxError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SandboxError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SandboxTimeoutError(
                    "Timeout exceeded when calling POST /v1/util/convert_to_markdown.",
                );
            case "unknown":
                throw new errors.SandboxError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }
}
