// This file was auto-generated by Fern from our API Definition.

import type * as core from "../../../../../core/index.js";

/**
 * @example
 *     {}
 */
export interface BodyRegisterSkills {
    file?: core.file.Uploadable | undefined;
    path?: string;
    name?: string;
}
