// This file was auto-generated by Fern from our API Definition.

export const RecordAction = {
    Once: "once",
    Start: "start",
    Pause: "pause",
    Resume: "resume",
    Stop: "stop",
    Status: "status",
} as const;
export type RecordAction = (typeof RecordAction)[keyof typeof RecordAction];
