// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         path: "path"
 *     }
 */
export interface CreateWatchRequest {
    /** 监听目录路径 */
    path: string;
    /** 是否递归子目录 */
    recursive?: boolean;
    /** 排除的目录/glob 模式 */
    exclude?: string[];
    /** 去抖动窗口(ms) */
    debounce?: number;
    /** glob 过滤，空=全部通过 */
    include_patterns?: string[];
}
