// This file was auto-generated by Fern from our API Definition.

import type * as Sandbox from "../../../../index.js";

/**
 * @example
 *     {
 *         path: "path"
 *     }
 */
export interface FileWatchWaitRequest {
    /** 等待的文件路径（精确匹配） */
    path: string;
    /** 最大等待秒数 */
    timeout?: number;
    /** 关注的事件类型 */
    event_types?: Sandbox.FileWatchWaitRequestEventTypesItem[];
}
