// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface PollRequest {
    /** 上次游标 */
    since?: number;
    /** 最多返回条数 */
    limit?: number;
    /** 长轮询等待秒数，0=立即返回 */
    timeout?: number;
}
