// This file was auto-generated by Fern from our API Definition.

/** Recording action: start, stop, or status */
export const DisplayAction = {
    Start: "start",
    Stop: "stop",
    Status: "status",
} as const;
export type DisplayAction = (typeof DisplayAction)[keyof typeof DisplayAction];
