// This file was auto-generated by Fern from our API Definition.

/** Recording action: start, stop, or status */
export const RecordAction = {
    Start: "start",
    Stop: "stop",
    Status: "status",
} as const;
export type RecordAction = (typeof RecordAction)[keyof typeof RecordAction];
