// This file was auto-generated by Fern from our API Definition.

import { Browser } from "./api/resources/browser/client/Client.js";
import { Code } from "./api/resources/code/client/Client.js";
import { File_ } from "./api/resources/file/client/Client.js";
import { Jupyter } from "./api/resources/jupyter/client/Client.js";
import { Mcp } from "./api/resources/mcp/client/Client.js";
import { Nodejs } from "./api/resources/nodejs/client/Client.js";
import { SandboxService } from "./api/resources/sandbox/client/Client.js";
import { Shell } from "./api/resources/shell/client/Client.js";
import { Skills } from "./api/resources/skills/client/Client.js";
import { Util } from "./api/resources/util/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { mergeHeaders } from "./core/headers.js";
import * as core from "./core/index.js";
import * as errors from "./errors/index.js";

export declare namespace SandboxClient {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class SandboxClient {
    protected readonly _options: SandboxClient.Options;
    protected _sandbox: SandboxService | undefined;
    protected _shell: Shell | undefined;
    protected _file: File_ | undefined;
    protected _jupyter: Jupyter | undefined;
    protected _nodejs: Nodejs | undefined;
    protected _mcp: Mcp | undefined;
    protected _browser: Browser | undefined;
    protected _code: Code | undefined;
    protected _util: Util | undefined;
    protected _skills: Skills | undefined;

    constructor(_options: SandboxClient.Options) {
        this._options = {
            ..._options,
            logging: core.logging.createLogger(_options?.logging),
            headers: mergeHeaders(
                {
                    "X-Fern-Language": "JavaScript",
                    "X-Fern-Runtime": core.RUNTIME.type,
                    "X-Fern-Runtime-Version": core.RUNTIME.version,
                },
                _options?.headers,
            ),
        };
    }

    public get sandbox(): SandboxService {
        return (this._sandbox ??= new SandboxService(this._options));
    }

    public get shell(): Shell {
        return (this._shell ??= new Shell(this._options));
    }

    public get file(): File_ {
        return (this._file ??= new File_(this._options));
    }

    public get jupyter(): Jupyter {
        return (this._jupyter ??= new Jupyter(this._options));
    }

    public get nodejs(): Nodejs {
        return (this._nodejs ??= new Nodejs(this._options));
    }

    public get mcp(): Mcp {
        return (this._mcp ??= new Mcp(this._options));
    }

    public get browser(): Browser {
        return (this._browser ??= new Browser(this._options));
    }

    public get code(): Code {
        return (this._code ??= new Code(this._options));
    }

    public get util(): Util {
        return (this._util ??= new Util(this._options));
    }

    public get skills(): Skills {
        return (this._skills ??= new Skills(this._options));
    }

    /**
     * Serve the terminal HTML page
     *
     * @param {SandboxClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.serveTerminalTerminalGet()
     */
    public serveTerminalTerminalGet(requestOptions?: SandboxClient.RequestOptions): core.HttpResponsePromise<any> {
        return core.HttpResponsePromise.fromPromise(this.__serveTerminalTerminalGet(requestOptions));
    }

    private async __serveTerminalTerminalGet(
        requestOptions?: SandboxClient.RequestOptions,
    ): Promise<core.WithRawResponse<any>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "terminal",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.SandboxError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SandboxError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SandboxTimeoutError("Timeout exceeded when calling GET /terminal.");
            case "unknown":
                throw new errors.SandboxError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }
}
