// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as errors from "../../../../errors/index.js";
import * as Sandbox from "../../../index.js";

export declare namespace Jupyter {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class Jupyter {
    protected readonly _options: Jupyter.Options;

    constructor(_options: Jupyter.Options) {
        this._options = _options;
    }

    /**
     * Execute Python code using Jupyter kernel with session persistence
     *
     * This endpoint allows you to execute Python code and get results back.
     * You can optionally specify a kernel_name (defaults to 'python3').
     * Use session_id to maintain variable state across multiple requests.
     * Sessions automatically expire after 30 minutes of inactivity.
     *
     * @param {Sandbox.JupyterExecuteRequest} request
     * @param {Jupyter.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Sandbox.UnprocessableEntityError}
     *
     * @example
     *     await client.jupyter.executeCode({
     *         code: "code"
     *     })
     */
    public executeCode(
        request: Sandbox.JupyterExecuteRequest,
        requestOptions?: Jupyter.RequestOptions,
    ): core.HttpResponsePromise<Sandbox.ResponseJupyterExecuteResponse> {
        return core.HttpResponsePromise.fromPromise(this.__executeCode(request, requestOptions));
    }

    private async __executeCode(
        request: Sandbox.JupyterExecuteRequest,
        requestOptions?: Jupyter.RequestOptions,
    ): Promise<core.WithRawResponse<Sandbox.ResponseJupyterExecuteResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/jupyter/execute",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as Sandbox.ResponseJupyterExecuteResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Sandbox.UnprocessableEntityError(
                        _response.error.body as Sandbox.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.SandboxError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SandboxError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SandboxTimeoutError("Timeout exceeded when calling POST /v1/jupyter/execute.");
            case "unknown":
                throw new errors.SandboxError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Get information about available Jupyter kernels
     *
     * @param {Jupyter.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.jupyter.getInfo()
     */
    public getInfo(
        requestOptions?: Jupyter.RequestOptions,
    ): core.HttpResponsePromise<Sandbox.ResponseJupyterInfoResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getInfo(requestOptions));
    }

    private async __getInfo(
        requestOptions?: Jupyter.RequestOptions,
    ): Promise<core.WithRawResponse<Sandbox.ResponseJupyterInfoResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/jupyter/info",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Sandbox.ResponseJupyterInfoResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.SandboxError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SandboxError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SandboxTimeoutError("Timeout exceeded when calling GET /v1/jupyter/info.");
            case "unknown":
                throw new errors.SandboxError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * List all active Jupyter sessions
     *
     * @param {Jupyter.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.jupyter.listSessions()
     */
    public listSessions(
        requestOptions?: Jupyter.RequestOptions,
    ): core.HttpResponsePromise<Sandbox.ResponseActiveSessionsResult> {
        return core.HttpResponsePromise.fromPromise(this.__listSessions(requestOptions));
    }

    private async __listSessions(
        requestOptions?: Jupyter.RequestOptions,
    ): Promise<core.WithRawResponse<Sandbox.ResponseActiveSessionsResult>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/jupyter/sessions",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Sandbox.ResponseActiveSessionsResult, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.SandboxError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SandboxError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SandboxTimeoutError("Timeout exceeded when calling GET /v1/jupyter/sessions.");
            case "unknown":
                throw new errors.SandboxError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Cleanup all active sessions
     *
     * @param {Jupyter.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.jupyter.deleteSessions()
     */
    public deleteSessions(requestOptions?: Jupyter.RequestOptions): core.HttpResponsePromise<Sandbox.Response> {
        return core.HttpResponsePromise.fromPromise(this.__deleteSessions(requestOptions));
    }

    private async __deleteSessions(
        requestOptions?: Jupyter.RequestOptions,
    ): Promise<core.WithRawResponse<Sandbox.Response>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/jupyter/sessions",
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Sandbox.Response, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.SandboxError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SandboxError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SandboxTimeoutError("Timeout exceeded when calling DELETE /v1/jupyter/sessions.");
            case "unknown":
                throw new errors.SandboxError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Manually cleanup a specific session
     *
     * @param {string} sessionId
     * @param {Jupyter.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Sandbox.UnprocessableEntityError}
     *
     * @example
     *     await client.jupyter.deleteSession("session_id")
     */
    public deleteSession(
        sessionId: string,
        requestOptions?: Jupyter.RequestOptions,
    ): core.HttpResponsePromise<Sandbox.Response> {
        return core.HttpResponsePromise.fromPromise(this.__deleteSession(sessionId, requestOptions));
    }

    private async __deleteSession(
        sessionId: string,
        requestOptions?: Jupyter.RequestOptions,
    ): Promise<core.WithRawResponse<Sandbox.Response>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v1/jupyter/sessions/${core.url.encodePathParam(sessionId)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Sandbox.Response, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Sandbox.UnprocessableEntityError(
                        _response.error.body as Sandbox.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.SandboxError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SandboxError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SandboxTimeoutError(
                    "Timeout exceeded when calling DELETE /v1/jupyter/sessions/{session_id}.",
                );
            case "unknown":
                throw new errors.SandboxError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Create a new Jupyter session
     *
     * @param {Sandbox.JupyterCreateSessionRequest} request
     * @param {Jupyter.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Sandbox.UnprocessableEntityError}
     *
     * @example
     *     await client.jupyter.createSession()
     */
    public createSession(
        request: Sandbox.JupyterCreateSessionRequest = {},
        requestOptions?: Jupyter.RequestOptions,
    ): core.HttpResponsePromise<Sandbox.ResponseJupyterCreateSessionResponse> {
        return core.HttpResponsePromise.fromPromise(this.__createSession(request, requestOptions));
    }

    private async __createSession(
        request: Sandbox.JupyterCreateSessionRequest = {},
        requestOptions?: Jupyter.RequestOptions,
    ): Promise<core.WithRawResponse<Sandbox.ResponseJupyterCreateSessionResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/jupyter/sessions/create",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as Sandbox.ResponseJupyterCreateSessionResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Sandbox.UnprocessableEntityError(
                        _response.error.body as Sandbox.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.SandboxError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SandboxError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SandboxTimeoutError("Timeout exceeded when calling POST /v1/jupyter/sessions/create.");
            case "unknown":
                throw new errors.SandboxError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }
}
