// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as errors from "../../../../errors/index.js";
import * as Sandbox from "../../../index.js";

export declare namespace Browser {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class Browser {
    protected readonly _options: Browser.Options;

    constructor(_options: Browser.Options) {
        this._options = _options;
    }

    /**
     * Get information about browser, like cdp url, viewport size, etc.
     *
     * @param {Browser.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.browser.getInfo()
     */
    public getInfo(
        requestOptions?: Browser.RequestOptions,
    ): core.HttpResponsePromise<Sandbox.ResponseBrowserInfoResult> {
        return core.HttpResponsePromise.fromPromise(this.__getInfo(requestOptions));
    }

    private async __getInfo(
        requestOptions?: Browser.RequestOptions,
    ): Promise<core.WithRawResponse<Sandbox.ResponseBrowserInfoResult>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/browser/info",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Sandbox.ResponseBrowserInfoResult, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.SandboxError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SandboxError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SandboxTimeoutError("Timeout exceeded when calling GET /v1/browser/info.");
            case "unknown":
                throw new errors.SandboxError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Take a screenshot of the current display.
     *
     * Returns:
     *     StreamingResponse: PNG image data with proper headers including display and screenshot dimensions
     */
    public screenshot(requestOptions?: Browser.RequestOptions): core.HttpResponsePromise<core.BinaryResponse> {
        return core.HttpResponsePromise.fromPromise(this.__screenshot(requestOptions));
    }

    private async __screenshot(
        requestOptions?: Browser.RequestOptions,
    ): Promise<core.WithRawResponse<core.BinaryResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)<core.BinaryResponse>({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/browser/screenshot",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            responseType: "binary-response",
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.SandboxError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SandboxError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SandboxTimeoutError("Timeout exceeded when calling GET /v1/browser/screenshot.");
            case "unknown":
                throw new errors.SandboxError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Execute a validated action on the current display.
     *
     * @param {Sandbox.Action} request
     * @param {Browser.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Sandbox.UnprocessableEntityError}
     *
     * @example
     *     await client.browser.executeAction({
     *         action_type: "MOVE_TO",
     *         x: 1.1,
     *         y: 1.1
     *     })
     */
    public executeAction(
        request: Sandbox.Action,
        requestOptions?: Browser.RequestOptions,
    ): core.HttpResponsePromise<Sandbox.ActionResponse> {
        return core.HttpResponsePromise.fromPromise(this.__executeAction(request, requestOptions));
    }

    private async __executeAction(
        request: Sandbox.Action,
        requestOptions?: Browser.RequestOptions,
    ): Promise<core.WithRawResponse<Sandbox.ActionResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/browser/actions",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Sandbox.ActionResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Sandbox.UnprocessableEntityError(
                        _response.error.body as Sandbox.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.SandboxError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SandboxError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SandboxTimeoutError("Timeout exceeded when calling POST /v1/browser/actions.");
            case "unknown":
                throw new errors.SandboxError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Execute a validated action on the current display.
     *
     * @param {Sandbox.BrowserConfigRequest} request
     * @param {Browser.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Sandbox.UnprocessableEntityError}
     *
     * @example
     *     await client.browser.setConfig()
     */
    public setConfig(
        request: Sandbox.BrowserConfigRequest = {},
        requestOptions?: Browser.RequestOptions,
    ): core.HttpResponsePromise<Sandbox.Response> {
        return core.HttpResponsePromise.fromPromise(this.__setConfig(request, requestOptions));
    }

    private async __setConfig(
        request: Sandbox.BrowserConfigRequest = {},
        requestOptions?: Browser.RequestOptions,
    ): Promise<core.WithRawResponse<Sandbox.Response>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/browser/config",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Sandbox.Response, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Sandbox.UnprocessableEntityError(
                        _response.error.body as Sandbox.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.SandboxError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SandboxError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SandboxTimeoutError("Timeout exceeded when calling POST /v1/browser/config.");
            case "unknown":
                throw new errors.SandboxError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }
}
