name: Push Docker Image to GHCR

on:
  workflow_dispatch:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  push-to-ghcr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Pull source image
        id: pull
        run: |
          # For releases, use the version tag; otherwise use latest
          if [[ "${{ github.event_name }}" == "release" ]]; then
            # Remove 'v' prefix from tag name (e.g., v1.0.0.1 -> 1.0.0.1)
            VERSION="${{ github.event.release.tag_name }}"
            VERSION="${VERSION#v}"
            docker pull enterprise-public-cn-beijing.cr.volces.com/vefaas-public/all-in-one-sandbox:${VERSION}
            echo "source_tag=${VERSION}" >> "$GITHUB_OUTPUT"
          else
            docker pull enterprise-public-cn-beijing.cr.volces.com/vefaas-public/all-in-one-sandbox:latest
            echo "source_tag=latest" >> "$GITHUB_OUTPUT"
          fi

      - name: Tag image for GHCR
        run: |
          # Always tag as v1
          docker tag enterprise-public-cn-beijing.cr.volces.com/vefaas-public/all-in-one-sandbox:${{ steps.pull.outputs.source_tag }} \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:v1

          # For releases, also tag with the version number
          if [[ "${{ github.event_name }}" == "release" ]]; then
            VERSION="${{ github.event.release.tag_name }}"
            VERSION="${VERSION#v}"
            docker tag enterprise-public-cn-beijing.cr.volces.com/vefaas-public/all-in-one-sandbox:${{ steps.pull.outputs.source_tag }} \
              ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${VERSION}
          fi

      - name: Push image to GHCR
        run: |
          # Always push v1 tag
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:v1

          # For releases, push the version tag
          if [[ "${{ github.event_name }}" == "release" ]]; then
            VERSION="${{ github.event.release.tag_name }}"
            VERSION="${VERSION#v}"
            docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${VERSION}
          fi
